Add dummy final score page
ia-toki/bebras-pandai pull request #36
Opened 2023-10-22 08:15 UTC by gmochid

# Description
Dummy Final Score Page

# From Task
- #30 view only

2023-10-24 02:42 UTC, atnanahidiw reviewed
please check #30 again, I need your feedback in the discussion 🙇

2023-10-24 02:42 UTC, atnanahidiw commented on app/lib/features/final_score/final_score_page.dart
> +                    Text('MANTAP!!!')
could the 20, 3, 10, & MANTAP!!! be parameterized in this PR? (maybe has default values)
let's just name the variable:
- `score`
- `n_answer_correct`
- `n_answer_incorrect`

also
<img width="518" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1970083/8bc83093-a7b9-4e1a-911b-ea7284e90e45">
( see #30 )

2023-11-06 02:50 UTC, gmochid commented
Monggo review @atnanahidiw

2023-11-06 04:31 UTC, atnanahidiw requested changes
ada yg salah ngeresolve pas conflict bung @gmochid 
yg `Assets.bebrasMascot` perlu diganti jadi `Assets.bebrasPandaiText`
bentukane mascot kaya gini soale, CMIIW 🙇
<img width="403" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1970083/1909e290-c0f7-42bc-a3a5-04ba438d225c">

2023-11-06 04:31 UTC, atnanahidiw commented on app/lib/core/constants/assets.dart
> -  static const bebrasPandaiText = 'assets/images/bebras-banner.png';
Ini kehapus ya bung @gmochid? Bisa direvert?
Sama yg bawah2 juga perlu direvert juga 🙇
<img width="369" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1970083/34d8a9da-09c3-4a17-b39f-67f987158d2f">

2023-11-06 04:31 UTC, atnanahidiw commented on app/lib/features/quiz_registration/presentation/pages/quiz_registration_page.dart
> +        if (weeklyQuizParticipant.attempts.length ==
```suggestion
        if (weeklyQuizParticipant.attempts.length >=
```

2023-11-06 04:31 UTC, atnanahidiw commented on app/lib/features/quiz_registration/presentation/pages/quiz_registration_page.dart
> +        if (weeklyQuizParticipant.attempts.length ==
bisa handle kalau2 kelebihan 😆

2023-11-06 04:31 UTC, atnanahidiw commented on app/lib/features/quiz_registration/presentation/pages/quiz_registration_page.dart
> +          );
kondisi yg ini dihapus aja gimana? nyicil, kayanya kedepannya bikin error kalau maxAttempt > 1

2023-11-06 04:31 UTC, atnanahidiw commented on app/lib/services/quiz_service.dart
> +      FirebaseFirestore.instance.collection('registered_user');
kayanya yg dibawah2 uda diganti `db.collection` semua
bisa dihapus 🙇

2023-11-06 05:40 UTC, gmochid commented on app/lib/features/quiz_registration/presentation/pages/quiz_registration_page.dart
> +          );
Sebenernya ini masih dummy sih, soalnya halamannya bisa beda. Misalkan max attempt 5 tapi ini masih attempt kedua. Nah apakah masuk ke exercise atau bisa diset ke halaman lain

2023-11-06 07:51 UTC, atnanahidiw commented on app/lib/features/quiz_registration/presentation/pages/quiz_registration_page.dart
> +          );
oh I see, ini nanti kalau mau diredirect ke page lain dulu ya
okok 💯

2023-11-06 07:53 UTC, atnanahidiw approved these changes
LGTM 🚀

2023-11-07 01:56 UTC, merged