Task List for Admin
ia-toki/bebras-pandai pull request #91
Opened 2023-11-16 05:25 UTC by gmochid

#83

2023-11-16 11:18 UTC, atnanahidiw requested changes
kalau requestnya ga mungkin bisa dibalas dikomen ya bung @gmochid 🙇

2023-11-16 11:18 UTC, atnanahidiw commented on app/lib/features/quiz_exercise/presentation/repositories/quiz_exercise.dart
> +      final result = await db.collection('task_set').get();
ini mahal juga baca semua doc di `task_set` 💸
aku tambahin field baru di [configuration/global_variables](https://console.firebase.google.com/u/0/project/toki-bebras-proto/firestore/data/~2Fconfiguration~2Fglobal_variables) yg bakalan diupdate valuenya sama script yg ngupload task set
gimana kalau pakai `task_set_doc_index` itu aja?

2023-11-16 13:38 UTC, gmochid commented on app/lib/features/quiz_exercise/presentation/repositories/quiz_exercise.dart
> +      final result = await db.collection('task_set').get();
oke, bisa sih. nanti diganti ya

2023-11-16 13:39 UTC, gmochid commented on app/lib/features/task_detail/presentation/pages/task_detail_page.dart
> +    return BebrasScaffold(
perlu dibuat 1 component terpisah, tapi ini bisa

2023-11-16 13:42 UTC, gmochid commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                      return const SizedBox(
sudah coba dirun belum? Behavior yang tak buat sih kayak gini, unless emang mau dibikin beda. 
- Jika Admin -> render 130 + button + 20 -> total height-nya sekitar 200 juga
- Jika bukan Admin -> render height 200

Kalau beda, mungkin bisa minta design-nya biar clear

2023-11-16 19:17 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                      return const SizedBox(
O iya ding, sorry2 blunder

2023-11-22 02:00 UTC, atnanahidiw requested changes

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/home_page.dart
> -                                style: FontTheme.blackTitleBold(),
milihnya yg ini bung @gmochid, biar tulisannya mepet kiri
 kalau pake yg bawah jadi posisinya ditengah walaupun align kiri
 
 
<img width="512" alt="image" src="https://github.com/ia-toki/bebras-pandai/assets/1970083/1fb319b1-0e22-4424-adf7-80cc15694b33">

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                        height: 200,
```suggestion
                        height: MediaQuery.of(context).size.height - 695,
```

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                              height: 20,
```suggestion
                              height: 25,
```

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                              height: 130,
```suggestion
                              height: MediaQuery.of(context).size.height - 625,
```

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
>                    ),
```suggestion
```

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/services/router_service.dart
>        path: '/main',
```suggestion
      path: '/home',
```

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/services/router_service.dart
>        path: '/main',
biar konsisten 😆 minta tolong redirect yg pakai ini di page2 lain direplace juga ya

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
> +                              height: 130,
itungan kasar 695-(200-130) 😬

2023-11-22 02:00 UTC, atnanahidiw commented on app/lib/features/main/presentation/pages/setting_page.dart
>                    ),
ini dihapus aja

2023-11-25 02:51 UTC, merged